version: '3.7'
services:
  app:
    build: ./docker/app/
    tty: true
    volumes:
      - ./src:/go/src/work
    ports:
      - 1323:1323
    command: "go run server.go"
  db:
    image: mysql/mysql-server
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
